### ISSUE TITLE
bug: Datepicker DateLocale.firstDayOfWeek

### ISSUE THREAD

**Issue by JirkaBures** [liuy97/md2#5]
on old md2 version of datepicker, when i used locale service
constructor(private loc: DateLocale)

i could change
this.loc.firstDayOfWeek = 1;

this is broken here. It only changes weekdays headers, but not _weeks array itself.

I suspect
Md2MonthView._weeks
which differs from original version

**Comment by liuy97** [comment]
maybe.  However, it is better to provide a customized NativeDateAdapter class, if you want to change firstDayOfWeek.

**Comment by JirkaBures** [comment]
how to use, like this ?

... 
providers: [
        {provide: NativeDateAdapter, useClass: EsNativeDateAdapter},
    ]
})
export class EsFormModule {}

export class EsNativeDateAdapter extends NativeDateAdapter {
getFirstDayOfWeek(): number {
        return 1;
    }
}

this does nothing for me, am i missing something ?

**Comment by liuy97** [comment]
It is DateLocale (not NativeDateAdapter) in this library.

`
@Injectable()
export class MyDateLocale extends DateLocale {
    constructor() {
        super();
        this.firstDayOfWeek = 1;
    }
}
`

`providers: [
    {provide: DateLocale, useClass: MyDateLocale},
  ],`

**Comment by JirkaBures** [comment]
No matter how i set firstDayOfWeek, the _weeks array in Md2MonthView does in not reflect this.

**Comment by liuy97** [comment]
I have confirmed my solution works fine. You don't need to change inner objects directly.

**Comment by JirkaBures** [comment]
![monday](https://user-images.githubusercontent.com/23057048/59906087-17b68e80-9408-11e9-859b-7446dc5cfcd4.png)
![sunday](https://user-images.githubusercontent.com/23057048/59906088-184f2500-9408-11e9-9ebd-c47918bd126a.png)

**Comment by liuy97** [comment]
Thanks. I get it. I will have a look at this when I have time.

**Comment by liuy97** [comment]
@JirkaBures , Could you confirm this fix?

**Comment by JirkaBures** [comment]
Fixed. Thank you !
