### ISSUE TITLE
Angular v9 Support

### ISSUE THREAD

**Issue by Sanjaygpatel** [liuy97/md2#8]
We have upgraded our app  (angular version 8) to v9-RC10 and we are getting following error in @Angular Core. 

as Error TS2724 Module '"../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2' ?

import { EventEmitter, Elementref, OnDestory, Renderer, TemplateRef, ViewContainerRef } from '@angular/core'

node_modules/@angular/core/core.d.ts:5678:31
5678 export declare abstract class Renderer2 {

is there any alternative or solution for it ? do we have any release for Angular 9 in near future ?

**Comment by liuy97** [comment]
I have not tested Angular 9 RC 10 yet. Yes, If Angular 9 is officially released, I will upgrade it to Angular 9.
